-- Create sequences for primary keys
CREATE SEQUENCE IF NOT EXISTS competition_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS club_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS category_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS event_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS category_event_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS athlete_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS athlete_competition_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS result_seq START WITH 1 INCREMENT BY 1;
